name: echo_pod
description: A next-generation AI-powered podcast player.
version: 0.0.1+87

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  flex_color_scheme: ^7.3.1
  google_fonts: ^6.2.1
  flutter_widget_from_html: ^0.15.1

  # Audio core
  just_audio: ^0.9.38
  audio_service: ^0.18.15
  audio_video_progress_bar: ^2.0.3
  audio_session: ^0.1.21
  
  # Data & Networking
  dio: ^5.4.3+1
  webfeed_plus: ^1.1.0 # For RSS parsing
  html: ^0.15.4
  path_provider: ^2.1.3
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  shared_preferences: ^2.2.3
  diffutil_dart: ^3.0.0 # For list diffing

  # AI & Integration (Services)
  openai_dart: ^0.1.0-dev.14 # For AI summaries/chat
  share_plus: ^10.1.0 # For exporting files
  receive_sharing_intent: ^1.8.1 # For receiving shared files
  rxdart: ^0.28.0
  screenshot: ^3.0.0
  flutter_inappwebview: ^6.1.5
  video_player: ^2.9.5
  http: ^1.6.0
  flutter_staggered_grid_view: ^0.7.0
  animations: ^2.0.11
  m3e_collection: ^0.3.7
  cupertino_native_better: ^1.3.4
  cached_network_image: ^3.4.1
  connectivity_plus: ^7.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true

dependency_overrides:
  package_info_plus: ^8.3.0
  wakelock_plus: 1.2.9
  path_provider_android: 2.2.0
  sqflite_android: 2.4.0
  url_launcher_android: 6.2.0
  shared_preferences_android: 2.2.1
  webview_flutter_android: 3.13.0
